services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6379"